// Single source of truth for CoinGecko symbol → ID mapping
export const COINGECKO_ID_MAP: Record<string, string> = {
  BTC: "bitcoin",
  ETH: "ethereum",
  SOL: "solana",
  USDC: "usd-coin",
  MATIC: "matic-network",
  DOT: "polkadot",
  AVAX: "avalanche-2",
  LINK: "chainlink",
  SUI: "sui",
  DEEP: "deep",
  NS: "suins-token",
  ALGO: "algorand",
  MYTHOS: "mythos",
  WXM: "weatherxm-network",
  ANLOG: "analog",
  "0G": "zero-gravity",
  QUAI: "quai-network",
  BERA: "berachain-bera",
  MOVE: "movement",
  GRASS: "grass",
  EIGEN: "eigenlayer",
  CHEQ: "cheqd-network",
  AURORA: "aurora-near",
  AI3: "autonomys-network",
  BABY: "babylon",
  KITE: "kite-2",
  LSD: "pontem-liquidswap",
  SAHARA: "sahara-ai",
  SIGN: "sign-global",
  SOSO: "sosovalue",
  SXT: "space-and-time",
  UAI: "unifai-network",
  XTM: "minotari",
  MIRROR: "black-mirror",
};
